name: Deploy Dynamodb Lock 

on:
  push:
    branches:
      - master

jobs:
  terraform:
    name: Deploy Portfolio Website
    runs-on: ubuntu-latest
    env:
      working-directory: terraform
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
          
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "eu-west-1"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ dynamodb-lock.working-directory }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ dynamodb-lock.working-directory }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ dynamodb-lock.working-directory }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ dynamodb-lock.working-directory }}
